// Code generated by bilc from ../bil/examples/19-mesh-ripple.bil. To
// regenerate: (cd ../bil/tools/bilc/cmd/bilc && go build -o ../../bilc .) && \
//   ../bil/tools/bilc/bilc ../bil/examples/19-mesh-ripple.bil nodeprog/meshripple/main.go

//go:build js && wasm

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:26
package main

import "sync"

import "emulator/nodeprog/bilink"

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:27

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:28
import "time"

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:29

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:30
const waves = 3

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:31

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:32
// hopDelay is purely cosmetic -- the rendezvous itself already

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:33
// enforces correct pacing (both sides must be present), this just

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:34
// makes the ripple visible to a human watching the grid rather than

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:35
// resolving instantly.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:36
const hopDelay = 150 * time.Millisecond

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:37

func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:38
node() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:39
	r, c := bilink.Row(), bilink.Col()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:40
	cols := bilink.NumCols()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:41

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:42
	bilink.Screenf("(%d,%d) ready", r, c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:43

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:44
	if cols < 2 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:45
		bilink.Screenf("(%d,%d) single column, nothing to ripple", r, c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:46
		time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:46

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:47
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:48

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:49
	for wave := 0; wave < waves; wave++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:50
		if c == 0 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:51
			// originate the wave east, then await its reflection back via the same link

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:52
			time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:53
			bilink.Screenf("wave %d: send east = %d", wave, wave)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:54
			bilink.Send(1, int32(wave))
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:54

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:55
			var v int32

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:56
			v = bilink.Recv(1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:56

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:57
			bilink.Screenf("wave %d: reflected back = %d", wave, v)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:58
		} else if c == cols-1 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:59
			// last column: receive, then reflect straight back west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:60
			var v int32

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:61
			v = bilink.Recv(3)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:61

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:62
			bilink.Screenf("wave %d: got %d, reflecting", wave, v)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:63
			time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:64
			bilink.Send(3, v)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:65
		} else {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:66
			// middle: forward the wave east, then forward its reflection west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:67
			var v int32

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:68
			v = bilink.Recv(3)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:68

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:69
			bilink.Screenf("wave %d: got %d, forward east", wave, v)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:70
			time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:71
			bilink.Send(1, v)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:71

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:72

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:73
			var v2 int32

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:74
			v2 = bilink.Recv(1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:74

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:75
			bilink.Screenf("wave %d: reflection %d, forward west", wave, v2)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:76
			time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:77
			bilink.Send(3, v2)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:77

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:78
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:79
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:80

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:81
	bilink.Screenf("(%d,%d) done, %d waves complete", r, c, waves)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:82
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:82

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:83
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:84

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:85
// One Worker == one grid node (see static/index.html's buildTopology

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:86
// and node-worker.js in the emulator repo) -- the emulator spawns and

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:87
// positions all NxM instances itself, so this program's job is only to

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:88
// run the single node it's told it is via bilink.Row/Col, once. It

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:89
// must NOT enumerate the grid itself (no `par`/`par range` here): a

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:90
// replicated par would spawn N*M goroutines *within this one Worker*,

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:91
// all reading the same bilRow/bilCol and racing on the same link

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:92
// buffers -- confirmed by hitting exactly that bug (every node's

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:93
// screen showing 2-4x duplicated output) before landing on this.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:94
func main() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:95
	node()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/19-mesh-ripple.bil:96
}

func par(branches ...func()) {
	var wg sync.WaitGroup
	wg.Add(len(branches))
	for _, b := range branches {
		go func(b func()) {
			defer wg.Done()
			b()
		}(b)
	}
	wg.Wait()
}

func parFor(n int, body func(int)) {
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func(i int) {
			defer wg.Done()
			body(i)
		}(i)
	}
	wg.Wait()
}

func makeChans[T any](n int) []chan T {
	cs := make([]chan T, n)
	for i := range cs {
		cs[i] = make(chan T)
	}
	return cs
}

func splitN[T any](s []T, n int) [][]T {
	chunk := len(s) / n
	out := make([][]T, n)
	for i := range n {
		lo := i * chunk
		hi := lo + chunk
		if i == n-1 {
			hi = len(s)
		}
		out[i] = s[lo:hi:hi]
	}
	return out
}
