// Code generated by bilc from ../bil/examples/18-mesh-ripple.bil. To
// regenerate: (cd ../bil/tools/bilc && go build -o bilc .) && \
//   ../bil/tools/bilc/bilc ../bil/examples/18-mesh-ripple.bil nodeprog/meshripple/main.go

//go:build js && wasm

package main

import "sync"

import "emulator/nodeprog/bilink"

import "time"

const (
	north = 0
	east  = 1
	south = 2
	west  = 3
)

const waves = 3

// hopDelay is purely cosmetic -- the rendezvous itself already
// enforces correct pacing (both sides must be present), this just
// makes the ripple visible to a human watching the grid rather than
// resolving instantly.
const hopDelay = 150 * time.Millisecond

func node() {
	r, c := bilink.Row(), bilink.Col()
	cols := bilink.NumCols()

	bilink.Screenf("(%d,%d) ready", r, c)

	if cols < 2 {
		bilink.Screenf("(%d,%d) single column, nothing to ripple", r, c)
		time.Sleep(1<<63 - 1)
	}

	for wave := 0; wave < waves; wave++ {
		if c == 0 {
			// originate the wave east, then await its reflection back via the same link
			time.Sleep(hopDelay)
			bilink.Screenf("wave %d: send east = %d", wave, wave)
			bilink.Send(east, int32(wave))
			var v int32
			v = bilink.Recv(east)
			bilink.Screenf("wave %d: reflected back = %d", wave, v)
		} else if c == cols-1 {
			// last column: receive, then reflect straight back west
			var v int32
			v = bilink.Recv(west)
			bilink.Screenf("wave %d: got %d, reflecting", wave, v)
			time.Sleep(hopDelay)
			bilink.Send(west, v)
		} else {
			// middle: forward the wave east, then forward its reflection west
			var v int32
			v = bilink.Recv(west)
			bilink.Screenf("wave %d: got %d, forward east", wave, v)
			time.Sleep(hopDelay)
			bilink.Send(east, v)

			var v2 int32
			v2 = bilink.Recv(east)
			bilink.Screenf("wave %d: reflection %d, forward west", wave, v2)
			time.Sleep(hopDelay)
			bilink.Send(west, v2)
		}
	}

	bilink.Screenf("(%d,%d) done, %d waves complete", r, c, waves)
	time.Sleep(1<<63 - 1)
}

// One Worker == one grid node (see static/index.html's buildTopology
// and node-worker.js in the emulator repo) -- the emulator spawns and
// positions all NxM instances itself, so this program's job is only to
// run the single node it's told it is via bilink.Row/Col, once. It
// must NOT enumerate the grid itself (no `par`/`par range` here): a
// replicated par would spawn N*M goroutines *within this one Worker*,
// all reading the same bilRow/bilCol and racing on the same link
// buffers -- confirmed by hitting exactly that bug (every node's
// screen showing 2-4x duplicated output) before landing on this.
func main() {
	node()
}

func par(branches ...func()) {
	var wg sync.WaitGroup
	wg.Add(len(branches))
	for _, b := range branches {
		go func(b func()) {
			defer wg.Done()
			b()
		}(b)
	}
	wg.Wait()
}

func parFor(n int, body func(int)) {
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func(i int) {
			defer wg.Done()
			body(i)
		}(i)
	}
	wg.Wait()
}

func makeChans[T any](n int) []chan T {
	cs := make([]chan T, n)
	for i := range cs {
		cs[i] = make(chan T)
	}
	return cs
}

func splitN[T any](s []T, n int) [][]T {
	chunk := len(s) / n
	out := make([][]T, n)
	for i := range n {
		lo := i * chunk
		hi := lo + chunk
		if i == n-1 {
			hi = len(s)
		}
		out[i] = s[lo:hi]
	}
	return out
}
