// Code generated by bilc from ../bil/examples/22-pipeline-transformer.bil. To
// regenerate: (cd ../bil/tools/bilc/cmd/bilc && go build -o ../../bilc .) && \
//   ../bil/tools/bilc/bilc ../bil/examples/22-pipeline-transformer.bil nodeprog/pipelinetransformer/main.go

//go:build js && wasm

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:52
package main

import "sync"

import "emulator/nodeprog/bilink"

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:53

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:54
import (

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:55
	"math"

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:56
	"time"
	//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:57
)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:58

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:59
const generations = 6

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:60
const vocabSize = 4

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:61
const dModel = 4

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:62
const dFF = 8

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:63
const stageRows = 4 // embed, attention, feed-forward, output

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:65
// hopDelay is purely cosmetic -- the rendezvous itself already forces

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:66
// correct pacing -- it just makes each hop visible on the grid.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:67
const hopDelay = 60 * time.Millisecond

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:68

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:69
var vocab = [vocabSize]string{"the", "cat", "sat", "mat"}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:70

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:71
// embedding, wq/wk/wv, w1/b1/w2/b2 and wo are the same fixed,

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:72
// hand-picked weights Example 21 used -- illustrative numbers for a

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:73
// from-scratch demo, not a trained model. The point of this example

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:74
// is the distributed dataflow architecture, not prediction quality.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:75
var embedding = [vocabSize][dModel]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:76
	{0.10, 0.20, 0.30, 0.40},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:77
	{0.40, 0.10, 0.20, 0.30},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:78
	{0.30, 0.40, 0.10, 0.20},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:79
	{0.20, 0.30, 0.40, 0.10},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:80
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:81

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:82
var wq = [dModel][dModel]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:83
	{1, 0, 0, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:84
	{0, 1, 1, 0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:85
	{1, 1, 0, 0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:86
	{0, 0, 1, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:87
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:88

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:89
var wk = [dModel][dModel]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:90
	{1, 1, 0, 0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:91
	{0, 0, 1, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:92
	{1, 0, 1, 0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:93
	{0, 1, 0, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:94
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:95

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:96
var wv = [dModel][dModel]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:97
	{1, 0, 1, 0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:98
	{0, 1, 0, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:99
	{1, 1, 1, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:100
	{0, 0, 0, 1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:101
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:102

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:103
var w1 = [dModel][dFF]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:104
	{0.2, -0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.3},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:105
	{-0.1, 0.2, 0.0, 0.3, 0.1, -0.2, 0.3, 0.0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:106
	{0.3, 0.0, -0.1, 0.2, 0.0, 0.3, -0.2, 0.1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:107
	{0.0, 0.3, 0.2, -0.1, 0.3, 0.0, 0.1, -0.2},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:108
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:109
var b1 = [dFF]float64{0.05, -0.05, 0.05, -0.05, 0.05, -0.05, 0.05, -0.05}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:110

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:111
var w2 = [dFF][dModel]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:112
	{0.2, -0.1, 0.1, 0.0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:113
	{-0.1, 0.2, 0.0, 0.1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:114
	{0.1, 0.0, 0.2, -0.1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:115
	{0.0, 0.1, -0.1, 0.2},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:116
	{0.2, 0.0, -0.1, 0.1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:117
	{0.0, 0.2, 0.1, -0.1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:118
	{-0.1, 0.1, 0.0, 0.2},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:119
	{0.1, -0.1, 0.2, 0.0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:120
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:121
var b2 = [dModel]float64{0, 0, 0, 0}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:122

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:123
var wo = [dModel][vocabSize]float64{

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:124
	{0.5, -0.2, 0.1, 0.0},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:125
	{0.0, 0.5, -0.2, 0.1},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:126
	{0.1, 0.0, 0.5, -0.2},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:127
	{-0.2, 0.1, 0.0, 0.5},

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:128
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:129

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:130
func wordAt(tok int) string { return vocab[tok%vocabSize] }

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:131

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:132
func posEncode(pos int) [dModel]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:133
	var pe [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:134
	for i := 0; i < dModel; i += 2 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:135
		freq := 1.0 / math.Pow(10000, float64(i)/float64(dModel))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:136
		pe[i] = math.Sin(float64(pos) * freq)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:137
		if i+1 < dModel {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:138
			pe[i+1] = math.Cos(float64(pos) * freq)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:139
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:140
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:141
	return pe

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:142
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:143

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:144
func add4(a, b [dModel]float64) [dModel]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:145
	var y [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:146
	for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:147
		y[i] = a[i] + b[i]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:148
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:149
	return y

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:150
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:151

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:152
func matVec4(w [dModel][dModel]float64, x [dModel]float64) [dModel]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:153
	var y [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:154
	for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:155
		sum := 0.0

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:156
		for j := 0; j < dModel; j++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:157
			sum += w[i][j] * x[j]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:158
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:159
		y[i] = sum

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:160
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:161
	return y

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:162
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:163

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:164
func dot4(a, b [dModel]float64) float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:165
	sum := 0.0

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:166
	for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:167
		sum += a[i] * b[i]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:168
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:169
	return sum

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:170
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:171

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:172
func softmax(scores []float64) []float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:173
	max := scores[0]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:174
	for _, s := range scores {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:175
		if s > max {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:176
			max = s

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:177
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:178
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:179
	out := make([]float64, len(scores))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:180
	sum := 0.0

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:181
	for i, s := range scores {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:182
		out[i] = math.Exp(s - max)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:183
		sum += out[i]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:184
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:185
	for i := range out {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:186
		out[i] /= sum

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:187
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:188
	return out

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:189
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:190

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:191
func relu(x float64) float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:192
	if x > 0 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:193
		return x

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:194
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:195
	return 0

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:196
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:197

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:198
func feedForward(x [dModel]float64) [dModel]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:199
	var hidden [dFF]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:200
	for j := 0; j < dFF; j++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:201
		sum := b1[j]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:202
		for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:203
			sum += x[i] * w1[i][j]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:204
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:205
		hidden[j] = relu(sum)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:206
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:207
	var out [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:208
	for k := 0; k < dModel; k++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:209
		sum := b2[k]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:210
		for j := 0; j < dFF; j++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:211
			sum += hidden[j] * w2[j][k]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:212
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:213
		out[k] = sum

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:214
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:215
	return out

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:216
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:217

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:218
func outputLogits(x [dModel]float64) [vocabSize]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:219
	var logits [vocabSize]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:220
	for k := 0; k < vocabSize; k++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:221
		sum := 0.0

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:222
		for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:223
			sum += x[i] * wo[i][k]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:224
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:225
		logits[k] = sum

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:226
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:227
	return logits

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:228
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:229

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:230
func argmax4(v [vocabSize]float64) int {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:231
	best := 0

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:232
	for i := 1; i < vocabSize; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:233
		if v[i] > v[best] {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:234
			best = i

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:235
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:236
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:237
	return best

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:238
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:239

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:240
// runAttention runs self-attention plus the first residual connection

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:241
// over a whole row's worth of already-embedded vectors -- exactly the

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:242
// attention half of Example 21's runTransformer, stopping short of

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:243
// the feed-forward/output steps, which happen two and three rows

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:244
// further south instead.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:245
func runAttention(xs [][dModel]float64) [][dModel]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:246
	cols := len(xs)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:247

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:248
	q := make([][dModel]float64, cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:249
	k := make([][dModel]float64, cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:250
	v := make([][dModel]float64, cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:251
	for c := 0; c < cols; c++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:252
		q[c] = matVec4(wq, xs[c])

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:253
		k[c] = matVec4(wk, xs[c])

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:254
		v[c] = matVec4(wv, xs[c])

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:255
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:256

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:257
	resid1 := make([][dModel]float64, cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:258
	for c := 0; c < cols; c++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:259
		scores := make([]float64, cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:260
		for j := 0; j < cols; j++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:261
			scores[j] = dot4(q[c], k[j]) / math.Sqrt(float64(dModel))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:262
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:263
		weights := softmax(scores)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:264

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:265
		var attnOut [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:266
		for j := 0; j < cols; j++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:267
			for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:268
				attnOut[i] += weights[j] * v[j][i]

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:269
			}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:270
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:271

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:272
		resid1[c] = add4(xs[c], attnOut)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:273
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:274

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:275
	return resid1

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:276
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:277

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:278
// sendVec/recvVec carry a whole [dModel]float64 vector across one

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:279
// genuine cross-Worker link, one component at a time -- the physical

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:280
// link fabric only carries a plain int32 per hop (see

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:281
// bilink.Send/Recv), the same "one int32 at a time" idiom Example 21

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:282
// used for scalar tokens, just repeated dModel times for a vector.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:283
// Each float64 crosses as its float32 bit pattern -- plenty of

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:284
// precision for this demo's hand-picked weights.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:285
func sendVec(idx int, v [dModel]float64) {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:286
	for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:287
		bilink.Send(idx, int32(math.Float32bits(float32(v[i]))))
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:287

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:288
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:289
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:290

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:291
func recvVec(idx int) [dModel]float64 {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:292
	var v [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:293
	for i := 0; i < dModel; i++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:294
		var bits int32

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:295
		bits = bilink.Recv(idx)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:295

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:296
		v[i] = float64(math.Float32frombits(uint32(bits)))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:297
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:298
	return v

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:299
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:300

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:301
// embedStage runs on every column of row 0: computes this

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:302
// generation's synthetic input token locally (the same

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:303
// (col+gen)%vocabSize convention Example 21's relay/rowEnd used),

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:304
// embeds it, adds its positional encoding, and hands the result south

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:305
// to row 1. Pure per-column work, no lateral communication at all --

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:306
// every column of row 0 runs this in parallel with every other

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:307
// column, unlike Example 21 where one processor did every column's

// embedding serially.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:308
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:309
embedStage() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:310
	c := bilink.Col()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:311
	bilink.Screenf("embed ready at col %d", c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:312

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:313
	for gen := 0; gen < generations; gen++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:314
		tok := (c + gen) % vocabSize

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:315
		x0 := add4(embedding[tok], posEncode(c))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:316
		time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:317
		sendVec(2, x0) // south, to row 1's attention stage

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:318
		bilink.Screenf("gen %d: embedded %q", gen, wordAt(tok))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:319
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:320

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:321
	bilink.Screenf("embed done")

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:322
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:322

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:323
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:324

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:325
// attnController runs at (1,0): the west end of the attention row.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:326
// It gets its own column's embedded vector straight from the north

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:327
// link, gathers every other column's vector via the row's own

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:328
// west/east relay chain (Example 21's relay idiom, generalized from

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:329
// one int32 per round to a whole [dModel]float64 per round), runs

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:330
// self-attention plus the first residual connection once the whole

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:331
// row has arrived, scatters each column's own result back out along

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:332
// the same relay chain, then forwards its own result south to row

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:333
// 2 -- exactly what every other attention-row column does with

// theirs.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:334
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:335
attnController(cols int) {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:336
	bilink.Screenf("attn controller ready, %d cols", cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:337

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:338
	for gen := 0; gen < generations; gen++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:339
		xs := make([][dModel]float64, cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:340
		xs[0] = recvVec(0) // from north

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:341

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:342
		for r := cols - 1; r >= 1; r-- {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:343
			time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:344
			xs[r] = recvVec(1) // east

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:345
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:346

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:347
		resid1 := runAttention(xs)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:348

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:349
		for s := 1; s < cols; s++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:350
			time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:351
			sendVec(1, resid1[s]) // east

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:352
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:353

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:354
		time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:355
		sendVec(2, resid1[0]) // south, to row 2

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:356
		bilink.Screenf("gen %d: attended", gen)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:357
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:358

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:359
	bilink.Screenf("attn controller done")

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:360
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:360

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:361
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:362

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:363
// attnRelay runs on every other attention-row column. For gather

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:364
// round r: if r is its own column it originates (its own vector,

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:365
// already in hand from row 0); if r is further east it forwards

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:366
// (receive east, forward west); otherwise that round isn't on its

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:367
// path. Scatter mirrors this going back east. Once it has its own

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:368
// final result it forwards that south to row 2. This is Example 21's

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:369
// relay proc, generalized from one int32 per round to a whole

// [dModel]float64 per round.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:370
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:371
attnRelay(cols int) {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:372
	c := bilink.Col()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:373
	bilink.Screenf("attn relay ready at col %d", c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:374

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:375
	for gen := 0; gen < generations; gen++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:376
		myVec := recvVec(0) // from north

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:377

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:378
		for r := cols - 1; r >= 1; r-- {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:379
			switch {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:380
			case r == c:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:381
				time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:382
				sendVec(3, myVec) // west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:383
			case r > c:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:384
				v := recvVec(1) // east

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:385
				time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:386
				sendVec(3, v) // west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:387
			}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:388
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:389

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:390
		var mine [dModel]float64

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:391
		for s := 1; s < cols; s++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:392
			switch {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:393
			case s == c:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:394
				mine = recvVec(3) // west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:395
			case s > c:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:396
				v := recvVec(3) // west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:397
				time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:398
				sendVec(1, v) // east

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:399
			}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:400
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:401

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:402
		time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:403
		sendVec(2, mine) // south, to row 2

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:404
		bilink.Screenf("gen %d: relayed", gen)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:405
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:406

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:407
	bilink.Screenf("attn relay done")

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:408
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:408

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:409
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:410

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:411
// attnRowEnd runs at (1,cols-1): the east end of the attention row.

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:412
// Source for exactly one gather round (its own column) and

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:413
// destination for exactly one scatter round, then forwards its own

// result south -- unlike attnRelay it needs no round loop at all.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:414
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:415
attnRowEnd(cols int) {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:416
	c := cols - 1

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:417
	bilink.Screenf("attn row-end ready at col %d", c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:418

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:419
	for gen := 0; gen < generations; gen++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:420
		myVec := recvVec(0) // from north

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:421
		time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:422
		sendVec(3, myVec) // west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:423

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:424
		mine := recvVec(3) // west

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:425
		time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:426
		sendVec(2, mine) // south, to row 2

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:427
		bilink.Screenf("gen %d: row-end relayed", gen)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:428
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:429

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:430
	bilink.Screenf("attn row-end done")

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:431
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:431

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:432
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:433

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:434
// ffnStage runs on every column of row 2: purely per-column work

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:435
// again, like embedStage -- receive the attention stage's residual

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:436
// output from north, run the feed-forward sub-layer plus its own

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:437
// residual connection, hand the result south to row 3. No lateral

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:438
// communication: every column of row 2 runs this fully in parallel

// with every other column.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:439
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:440
ffnStage() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:441
	c := bilink.Col()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:442
	bilink.Screenf("ffn ready at col %d", c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:443

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:444
	for gen := 0; gen < generations; gen++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:445
		resid1 := recvVec(0) // from north

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:446
		resid2 := add4(resid1, feedForward(resid1))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:447
		time.Sleep(hopDelay)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:448
		sendVec(2, resid2) // south, to row 3

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:449
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:450

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:451
	bilink.Screenf("ffn done")

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:452
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:452

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:453
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:454

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:455
// outputStage runs on every column of row 3, the pipeline's final

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:456
// stage: receive the feed-forward stage's output from north, project

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:457
// to vocabulary logits, argmax to a predicted token, done. The

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:458
// prediction never needs to travel anywhere else, since embedStage

// already knows (and logged) what token it started from.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:459
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:460
outputStage() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:461
	c := bilink.Col()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:462
	bilink.Screenf("output ready at col %d", c)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:463

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:464
	for gen := 0; gen < generations; gen++ {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:465
		resid2 := recvVec(0) // from north

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:466
		predicted := argmax4(outputLogits(resid2))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:467
		bilink.Screenf("gen %d: col %d -> %q", gen, c, wordAt(predicted))

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:468
	}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:469

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:470
	bilink.Screenf("output done")

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:471
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:471

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:472
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:473

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:474
// idle runs on every row at or beyond stageRows -- this demo's

// pipeline is only 4 rows deep.
//
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:475
func
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:476
idle() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:477
	bilink.Screenf("idle -- beyond the pipeline's %d rows", stageRows)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:478
	time.Sleep(1<<63 - 1)
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:478

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:479
}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:480

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:481
func main() {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:482
	r, cols := bilink.Row(), bilink.NumCols()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:483

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:484
	switch {
	case bilink.Row() == 1 && bilink.Col() == 0:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:486
		attnController(cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:487

	case bilink.Row() == 1 && bilink.Col() == cols-1:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:489
		attnRowEnd(cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:490

	default:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:492
		switch r {

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:493
		case 0:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:494
			embedStage()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:495
		case 1:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:496
			attnRelay(cols)

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:497
		case 2:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:498
			ffnStage()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:499
		case 3:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:500
			outputStage()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:501
		default:

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:502
			idle()

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:503
		}

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:504

	}
//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:505

//line /Users/stephenroe/Library/CloudStorage/Dropbox/ClaudeZone/bil/examples/22-pipeline-transformer.bil:506
}

func par(branches ...func()) {
	var wg sync.WaitGroup
	wg.Add(len(branches))
	for _, b := range branches {
		go func(b func()) {
			defer wg.Done()
			b()
		}(b)
	}
	wg.Wait()
}

func parFor(n int, body func(int)) {
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func(i int) {
			defer wg.Done()
			body(i)
		}(i)
	}
	wg.Wait()
}

func makeChans[T any](n int) []chan T {
	cs := make([]chan T, n)
	for i := range cs {
		cs[i] = make(chan T)
	}
	return cs
}

func splitN[T any](s []T, n int) [][]T {
	chunk := len(s) / n
	out := make([][]T, n)
	for i := range n {
		lo := i * chunk
		hi := lo + chunk
		if i == n-1 {
			hi = len(s)
		}
		out[i] = s[lo:hi:hi]
	}
	return out
}
